@echo off
setlocal enabledelayedexpansion

set "sourceDirectory=C:\Users\admin\Desktop\Purezento\TERRACOTTA POTS Inch"
set "targetDirectory=C:\Users\admin\Desktop\otss"

for /r "%sourceDirectory%" %%F in (.) do (
    set "folderPath=%%F"
    set "folderPath=!folderPath:%sourceDirectory%=%targetDirectory%!"
    echo mkdir "!folderPath!" >> makefolders.bat
)

echo Folder structure extracted and saved to makefolders.bat successfully.
mkdir "C:\Users\admin\Desktop\otss\." 
mkdir "C:\Users\admin\Desktop\otss\Century\." 
mkdir "C:\Users\admin\Desktop\otss\Century\PTPCG6I\." 
mkdir "C:\Users\admin\Desktop\otss\Century\PTPCS6I\." 
mkdir "C:\Users\admin\Desktop\otss\Gardeneria\." 
mkdir "C:\Users\admin\Desktop\otss\Gardeneria\PTPGAR1\." 
mkdir "C:\Users\admin\Desktop\otss\Gardeneria\PTPGAR2\." 
mkdir "C:\Users\admin\Desktop\otss\Gardeneria\PTPGAR3\." 
mkdir "C:\Users\admin\Desktop\otss\Gardeneria\PTPGAR4\." 
mkdir "C:\Users\admin\Desktop\otss\Gardeneria\PTPGAR4PS\." 
mkdir "C:\Users\admin\Desktop\otss\Gardeneria\PTPGAR4PS\New folder\." 
mkdir "C:\Users\admin\Desktop\otss\Jeanie\." 
mkdir "C:\Users\admin\Desktop\otss\Jeanie\PTPJB4I\." 
mkdir "C:\Users\admin\Desktop\otss\Jeanie\PTPJBL4I\." 
mkdir "C:\Users\admin\Desktop\otss\Jeanie\PTPJC5PS\." 
mkdir "C:\Users\admin\Desktop\otss\Jeanie\PTPJLP4I\." 
mkdir "C:\Users\admin\Desktop\otss\Jeanie\PTPJM4I\." 
mkdir "C:\Users\admin\Desktop\otss\Jeanie\PTPJSB4I\." 
mkdir "C:\Users\admin\Desktop\otss\Marabelle-not\." 
mkdir "C:\Users\admin\Desktop\otss\Marabelle-not\PTPMC3PS\." 
mkdir "C:\Users\admin\Desktop\otss\Marabelle-not\PTPMGR\." 
mkdir "C:\Users\admin\Desktop\otss\Marabelle-not\PTPMRG\." 
mkdir "C:\Users\admin\Desktop\otss\Marabelle-not\PTPMW\." 
mkdir "C:\Users\admin\Desktop\otss\Monaco\." 
mkdir "C:\Users\admin\Desktop\otss\Monaco\PTPMON4PS\." 
mkdir "C:\Users\admin\Desktop\otss\Monaco\PTPMONB\." 
mkdir "C:\Users\admin\Desktop\otss\Monaco\PTPMONGR\." 
mkdir "C:\Users\admin\Desktop\otss\Monaco\PTPMONM\." 
mkdir "C:\Users\admin\Desktop\otss\Monaco\PTPMONP\." 
mkdir "C:\Users\admin\Desktop\otss\Pebble\." 
mkdir "C:\Users\admin\Desktop\otss\Pebble\PTPPEB4PS\." 
mkdir "C:\Users\admin\Desktop\otss\Pebble\PTPPEBB\." 
mkdir "C:\Users\admin\Desktop\otss\Pebble\PTPPEBBL\." 
mkdir "C:\Users\admin\Desktop\otss\Pebble\PTPPEBGR\." 
mkdir "C:\Users\admin\Desktop\otss\Pebble\PTPPEBPR\." 
mkdir "C:\Users\admin\Desktop\otss\PTPDMTITD4I\." 
mkdir "C:\Users\admin\Desktop\otss\PTPJFSP4I\." 
mkdir "C:\Users\admin\Desktop\otss\PTPMESARG\." 
mkdir "C:\Users\admin\Desktop\otss\PTPTLP\." 
mkdir "C:\Users\admin\Desktop\otss\Smoky\." 
mkdir "C:\Users\admin\Desktop\otss\Smoky\PTPSRG\." 
mkdir "C:\Users\admin\Desktop\otss\Smoky\PTPSRPB\." 
mkdir "C:\Users\admin\Desktop\otss\Smoky\PTPSRTPB2PS\." 
mkdir "C:\Users\admin\Desktop\otss\Smoky\PTPSTPB\." 
mkdir "C:\Users\admin\Desktop\otss\Sunbeam\." 
mkdir "C:\Users\admin\Desktop\otss\Sunbeam\PTPSUN4PS\." 
mkdir "C:\Users\admin\Desktop\otss\Sunbeam\PTPSUNB\." 
mkdir "C:\Users\admin\Desktop\otss\Sunbeam\PTPSUNGR\." 
mkdir "C:\Users\admin\Desktop\otss\Sunbeam\PTPSUNM\." 
mkdir "C:\Users\admin\Desktop\otss\Sunbeam\PTPSUNPR\." 
mkdir "C:\Users\admin\Desktop\otss\Tiny\." 
mkdir "C:\Users\admin\Desktop\otss\Tiny\PTPTINY3PS\." 
mkdir "C:\Users\admin\Desktop\otss\Tiny\PTPTINYB\." 
mkdir "C:\Users\admin\Desktop\otss\Tiny\PTPTINYG\." 
mkdir "C:\Users\admin\Desktop\otss\Tiny\PTPTINYP\." 
mkdir "C:\Users\admin\Desktop\otss\Vespa\." 
mkdir "C:\Users\admin\Desktop\otss\Vespa\PTPV3PS\." 
mkdir "C:\Users\admin\Desktop\otss\Vespa\PTPVG\." 
mkdir "C:\Users\admin\Desktop\otss\Vespa\PTPVP\." 
mkdir "C:\Users\admin\Desktop\otss\Vespa\PTPVY\." 
